### ISSUE TITLE
Add lightbox to sessions preview images

### ISSUE THREAD

**Issue by Descent098** [Schulich-Ignite/website#213]
The current session preview images are hard to see on large screens. [Lightboxes](https://codepen.io/nsom/pen/VbqLew) would help make this easier to see

**Comment by andrewy94** [comment]
#227 

I implemented a working lightbox but I'm not sure if its exactly what we want. Hopefully I didn't break anything since I ended up adding new scripts to baseof.html

**Comment by Descent098** [comment]
Closed with #227
