### ISSUE TITLE
Difficulty Taxonomy

### ISSUE THREAD

**Issue by Descent098** [Schulich-Ignite/website#247]
It would be good to have a difficulty indicator for blog posts and definitions

## Fields

- Level (int): The difficulty level (i.e. 1)
- Sessions (list): Which sessions you should have completed (i.e. [beginner, flare])

## Overview page

- Include difficulty level at top
- Include concepts people should be aware of for this difficulty level (i.e. strings, variables, lists etc.)
- List of recent posts in that language
- List sessions that should have been completed

**Comment by b-smiley** [comment]
Is there a range for the difficulty? For instance, 1 is no coding required, and 10 is an advanced understanding of programming.

**Comment by Descent098** [comment]
@b-smiley the current plan to start is 1-3, 1 being concepts in beginner, 2 concepts in scorch, 3 concepts in web dev. But any other suggestions are welcome
